version: '3'
services:
  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass alex_rocks
    expose:
      - '6379'
    volumes:
      - ./.cache/redis:/data
    ports:
      - '6379:6379'
  postgres:
    image: postgres:latest
    ports:
      # Accessible from the host at port :35432
      - '35432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kickjump
    # Make sure log colors show up correctly
    tty: true
