[toolchain]

# Find versions: https://rust-lang.github.io/rustup-components-history/
channel = "nightly-2022-04-03"
components = [
  "cargo",
  "clippy",
  "llvm-tools-preview",
  "miri",
  "reproducible-artifacts",
  "rls",
  "rust-analysis",
  "rust-analyzer-preview",
  "rust-docs",
  "rust-std",
  "rustc",
  "rustc-dev",
  "rustc-docs",
  "rustfmt",
]
