<svg style:display="none">
  <filter
    id="icon-filter"
    filterUnits="objectBoundingBox"
    primitiveUnits="userSpaceOnUse"
    color-interpolation-filters="sRGB"
  >
    <feTurbulence
      baseFrequency="0.005"
      numOctaves={2}
      type="fractalNoise"
      seed="20"
      stitchTiles="noStitch"
      result="turbulenceResult"
    />
    <feDisplacementMap
      in="SourceGraphic"
      in2="turbulenceResult"
      xChannelSelector="B"
      yChannelSelector="A"
      scale="10"
      result="displacement"
    />
  </filter>
</svg>
