import { type InferGetStaticPropsType } from 'next';
import Link from 'next/link';

type ArticleListProps = InferGetStaticPropsType<typeof getStaticProps>;

const ArticleList = (props: ArticleListProps) => {
  const { articles } = props;

  return (
    <div className='wrapper'>
      <h1>All Posts</h1>
      <p>
        Click the link below to navigate to a page generated by <code>mdx-bundler</code>.
      </p>
      <ul>
        {articles?.map((post, index) => (
          <li key={index}>
            <Link href={`/articles/${post.slug}`}>{post.frontmatter.title}</Link>
          </li>
        ))}
      </ul>
    </div>
  );
};

export async function getStaticProps() {
  const { getAllArticles } = await import('~/utils/mdx');
  const articles = await getAllArticles();

  return { props: { articles } };
}

export default ArticleList;
