name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  PNPM_CACHE_FOLDER: '~/.pnpm-store'

jobs:
  # Lint the project
  lint:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup pnpm caching
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install and audit
        uses: ./.github/actions/pnpm
        with:
          cache: ${{ env.PNPM_CACHE_FOLDER }}

      - name: lint TS / JS files
        run: pnpm lint:es

      - name: check formatting
        run: pnpm lint:prettier

      - name: check repo and versions
        run: pnpm lint:repo

      - name: check build
        run: pnpm lint:build

  # Unit test and update coverage report
  unit_test:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup pnpm caching
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install and audit
        uses: ./.github/actions/pnpm
        with:
          cache: ${{ env.PNPM_CACHE_FOLDER }}

      - name: run unit tests
        run: pnpm test

  website_e2e:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup pnpm caching
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install and audit
        uses: ./.github/actions/pnpm
        with:
          cache: ${{ env.PNPM_CACHE_FOLDER }}

      - name: build kickjump.com
        run: pnpm build:kickjump.com

      - name: setup playwright test environment
        run: pnpm setup:playwright
        working-directory: tests/kickjump.com

      - name: run tests
        env:
          TEST_BUILD: 1
        run: pnpm test
        working-directory: tests/kickjump.com

  database_e2e:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup pnpm caching
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install and audit
        uses: ./.github/actions/pnpm
        with:
          cache: ${{ env.PNPM_CACHE_FOLDER }}

      - name: setup docker compose
        uses: isbang/compose-action@v1.0.0
        with:
          compose-file: docker-compose.yml

      - name: run tests
        run: pnpm test:db
        working-directory: tests

  # Build the project and run tests on built files.
  build_packages:
    timeout-minutes: 8
    runs-on: ubuntu-latest

    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup pnpm caching
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install and audit
        uses: ./.github/actions/pnpm
        with:
          cache: ${{ env.PNPM_CACHE_FOLDER }}

      - name: build packages
        run: pnpm build

      - name: upload typescript build
        uses: actions/upload-artifact@v2
        with:
          name: ts-build
          path: packages/*/dist/**
          retention-days: 1

  build_website:
    timeout-minutes: 8
    runs-on: ubuntu-latest

    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup pnpm caching
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup next.js caching
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/apps/kickjump.com/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install and audit
        uses: ./.github/actions/pnpm
        with:
          cache: ${{ env.PNPM_CACHE_FOLDER }}

      - name: build kickjump.com
        run: pnpm build:kickjump.com

      - name: upload typescript build
        uses: actions/upload-artifact@v2
        with:
          name: website-build
          path: app/kickjump.com/.next/**
          retention-days: 1

  build_unit_test:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 17]
      fail-fast: false

    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup pnpm caching
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install and audit
        uses: ./.github/actions/pnpm
        with:
          cache: ${{ env.PNPM_CACHE_FOLDER }}

      - name: build packages
        run: pnpm build

      - name: run unit tests
        run: pnpm test

  # Update package versions with changesets.
  changeset:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    if: ${{ false == contains(github.ref, 'changeset') && github.repository == 'kickjump/kickjump' }}
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup pnpm caching
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install and audit
        uses: ./.github/actions/pnpm
        with:
          cache: ${{ env.PNPM_CACHE_FOLDER }}

      - name: check versions are valid
        if: github.event.pull_request
        run: |
          pnpm version:pr
          pnpm version:ci
