name: deployment

on:
  workflow_run:
    workflows: [ci]
    types: [completed]

env:
  PNPM_CACHE_FOLDER: '~/.pnpm-store'

jobs:
  website:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: manage commit status
        uses: haya14busa/action-workflow_run-status@v1

      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: setup pnpm caching
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install and audit
        uses: ./.github/actions/pnpm
        with:
          cache: ${{ env.PNPM_CACHE_FOLDER }}

      - name: deploy staging website
        id: deploy-vercel-staging
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}

      - name: add staging comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          append: true
          message: |
            🚀 Deployed preview website for commit ${{github.sha}}: ${{ steps.deploy-vercel-staging.outputs.preview-url }}

      - name: setup playwright test environment
        env:
          TEST_BUILD: 1
        run: pnpm setup:tests
        working-directory: apps/kickjump.com

      - name: run tests on vercel
        env:
          WEBSITE_URL: ${{ steps.deploy-vercel-staging.outputs.preview-url }}
        run: pnpm test
        working-directory: apps/kickjump.com

      - name: deploy production
        uses: amondnet/vercel-action@v20
        if: github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.head_repository.full_name == 'kickjump/kickjump'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: '--prod'
